### ISSUE TITLE
Stage 1 functionalities progress

### ISSUE THREAD

**Issue by darrenldl** [daypack-dev/daypack#5]
- [x] Fixed events
- [x] Interleaving scheduling
  - See Time share scheduling strategy
- [x] Conflict resolution
  - Currently uses rollback to a previous version in the event of conflict
- [x] Usable time slots for tasks (or time slot whitelist)
- [ ] Predefined usable time slots profiles/aliases, e.g. weekdays, work hours, free time, sleep time
- [x] Scheduling strategies
  - [x] Fixed
  - [x] Shift
  - [x] Split and shift
  - [x] Split even
  - [x] Time share
  - [x] Push to
- [x] Bruteforcing schedule generator
- [x] Sorting scheduling requests based on flexibility score
- [x] Quota tracking
- [x] Schedule serialisation and deserialisation
- [x] Version control list
- [x] Progress tracking facilities
