### ISSUE TITLE
Cli frontend progress tracking

### ISSUE THREAD

**Issue by darrenldl** [daypack-dev/daypack#52]
Commands
- [ ] `sched`
- [ ] `dash`
  - Displays following sections
    - Missed task segment placements
    - Uncompleted tasks (say at most 5 of them, with remaining count at the bottom of the section)
    - Agenda of today and tomorrow (or more)
- [ ] `add`
  - [ ] `--task`
  - [ ] `--task-inst`
  - [ ] `--task-seg`
  - [ ] `--sched-req`
- [ ] `remove`
  - [ ] `--task`
  - [ ] `--task-inst`
  - [ ] `--task-seg`
  - [ ] `--sched-req`
- [x] `list`
  - [x] `--task`
  - [ ] `--task-completed`
  - [ ] `--task-discarded`
  - [ ] `--task-all`
  - [x] `--task-inst`
  - [ ] `--task-inst-completed`
  - [ ] `--task-inst-discarded`
  - [ ] `--task-inst-all`
  - [x] `--task-seg`
  - [ ] `--task-seg-completed`
  - [ ] `--task-seg-discarded`
  - [ ] `--task-seg-all`
  - [x] `--sched-req`
  - [ ] `--sched-req-completed`
  - [ ] `--sched-req-discarded`
  - [ ] `--sched-req-all`
- [ ] `search`
  - [ ] `--task`
  - [ ] `--task-inst`
  - [ ] `--task-seg`
  - [ ] `--by-task-id`
  - [ ] `--by-task-inst-id`
  - [ ] `--by-task-seg-id`
- [ ] `discard`
  - [ ] `--task`
  - [ ] `--task-inst`
  - [ ] `--task-seg`
  - [ ] `--sched-req`
- [ ] `done`
  - [ ] `--task`
  - [ ] `--task-inst`
  - [ ] `--task-seg`
- [ ] `undone`
  - [ ] `--task`
  - [ ] `--task-inst`
  - [ ] `--task-seg`
- [ ] `start`
  - [ ] `--task-inst`
  - [ ] `--task-seg`
- [ ] `stop`
  - [ ] `--task-inst`
  - [ ] `--task-seg`
- [ ] `progress`
  - [ ] `--task-inst`
  - [ ] `--task-seg`
- [ ] `agenda`
  - [ ] `--day`
  - [ ] `--week`
  - [ ] `--free-only`
  - [ ] `--free-and-used`
- [ ] `time-profile`
