### ISSUE TITLE
Stage 2 functionalities progress

### ISSUE THREAD

**Issue by darrenldl** [daypack-dev/daypack#6]
- [ ] Skipped period for recurrence (see #1)
- [ ] Priority
- [ ] Sorting scheduling requests based on priority level
- [ ] Respect splitable attribute
- [ ] Handle parallelisable tasks
- [ ] Tagging
